
name: Push development client app to Heroku

on:
  push:
    branches:
      - develop
      - feature/AddDeployAction
    paths:
      - '**'
      - '!apps/**'
      - 'apps/client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # manually deploy to Heroku
    # - name: Add client remote origin
    #   run: git remote add heroku-client https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME_DEV_CLIENT }}.git
    # - name: Deploy client to Heroku
    #   run: |
    #     git filter-branch -- --all
    #     git push heroku-client [branch_name]:refs/heads/master --force

    # deploy to Heroku
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV_CLIENT }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: "feature/AddDeployAction"
