name: Test

on: [push]

jobs:
  test-all:
    # Name the Job
    name: Test all Apps & Libs
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
      
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2

      # use correct node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs the build script
      - run: yarn --frozen-lockfile
      - run: yarn build:libs
      - run: yarn test
        env:
          CI: true